server:
  port: 80

spring:
  application:
    name: cloud-consuml-order

  cloud:
    # consul注册地址
    consul:
      host: 47.110.247.184
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        # 出掉去前端页面查看时爆红叉
        heartbeat:
          enabled: true